image: Visual Studio 2015

environment:
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32

clone_depth: 10

install:
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "pacman -Syu --noconfirm"
  - taskkill /f /fi "MODULES eq msys-2.0.dll"
  - bash -lc "pacman -Syu --noconfirm"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - set PATH=C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%
  - bash ./unixbuild.sh

deploy:
  provider: GitHub
  force_update: true
  auth_token:
    secure: zSJnpSnrKY1NO5RPVBaD/uq7UPyc+GW7ecjPFqEMsLjtnd6H+iNfROdoeuxJgt5T
  artifact: Binaries
  prerelease: true
  on:
    appveyor_repo_tag: true

artifacts:
  - path: dist\**\*.zip
    name: Binaries
